# Generated by Django 4.0.6 on 2022-08-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_about_beauty_birthday_event_fashion_wedding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='beauty',
            name='image',
            field=models.ImageField(upload_to='static/capzvisuals/image/beauty'),
        ),
    ]
