# Generated by Django 3.2.7 on 2022-08-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
