# Generated by Django 3.2.7 on 2022-08-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_comment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='image',
            field=models.ImageField(null=True, upload_to='static/capzvisuals/image/beauty/'),
        ),
    ]
