# Generated by Django 3.2.7 on 2022-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_beauty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beauty/'),
        ),
    ]
