# Generated by Django 3.2.7 on 2022-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_beauty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beauty',
            name='sample_chapter',
            field=models.FileField(blank=True, null=True, upload_to='beauty/%Y/%m/%D/'),
        ),
    ]
