# Generated by Django 3.2.7 on 2022-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_beauty_sample_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beauty',
            name='sample_chapter',
        ),
        migrations.AddField(
            model_name='beauty',
            name='message',
            field=models.CharField(max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='beauty',
            name='username',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
