# Generated by Django 3.2.7 on 2022-08-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20220807_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beauty',
            name='message',
        ),
        migrations.RemoveField(
            model_name='beauty',
            name='username',
        ),
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='birthday/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fashion/'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wedding/'),
        ),
    ]
